### ISSUE TITLE
Error in code in org-mode-map

### ISSUE THREAD

**Issue by JamesAAllsopp** [james-stoup/emacs-org-mode-tutorial#1]
GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6)

Debugger entered--Lisp error: (void-variable org-mode-map)
  (define-key org-mode-map (kbd "C-c <up>") 'org-priority-up)
  eval-buffer(#<buffer  *load*> nil "/home/james/.emacs" nil t)  ; Reading at buffer position 1113
  load-with-code-conversion("/home/james/.emacs" "/home/james/.emacs" t t)
  load("~/.emacs" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x14c248b8ffeda3aa>) #f(compiled-function () #<bytecode -0x1f3c686ddc0cdc35>) t)
  command-line()
  normal-top-level()

Just copied your config (first two parts) into my .emacs and I get this error. I think it's a quoting issue. Thanks for the guide!

**Comment by james-stoup** [comment]
I don't get that error, but I'm still on Emacs 27. So I'm installing 28 now and will update shortly.

**Comment by james-stoup** [comment]
I updated the [org-mode-config.el](https://github.com/james-stoup/emacs-org-mode-tutorial/blob/main/org-mode-config.el) file with something that might help you, but I am unable to reproduce your error. Can you give me the exact contents of your init file so I can try to reproduce this?

**Comment by james-stoup** [comment]
Closing this since I haven't heard anything else about it.
